firstnumber = input("Введите первое число в бинарном формате ")
secondnumber = input('Введите второе число в бинарном формате ') 
Multiplication = int(firstnumber, 2) * int(secondnumber, 2)
binaryMul = str(bin(Multiplication))
print("\nУмножение = " + binaryMul[2:])